// import NavBar from "@/component/NavBar";
import NavBar from '../component/NavBar';
import Footer from '../component/footer';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import '../styles/globals.css';
import '../styles/navBar.css';
import '../styles/homePage.css';
import '../styles/globals.css';
import '../styles/interiors.css';
import '../styles/Footer.css';
import 'bootstrap/dist/css/bootstrap.min.css';

const titleMap = {
    '/': 'VI Design Studio',
    '/interiors': 'INTERIORS | VI Design Studio',
    '/land-scape': 'LANDSCAPE | VI Design Studio',
    '/architecture': 'ARCHITECTURE | VI Design Studio',
    '/project': 'PROJECT | VI Design Studio',
    '/contact': 'CONTACT | VI Design Studio',
};

function MyApp({ Component, pageProps }) {
    const router = useRouter();
    const [title, setTitle] = useState('VI Design Studio');

    useEffect(() => {
        const handleRouteChange = (url) => {
            const pageTitle = titleMap[url] || 'VI Design Studio';
            setTitle(pageTitle);
        };

        handleRouteChange(router.pathname);

        router.events.on('routeChangeComplete', handleRouteChange);

        return () => {
            router.events.off('routeChangeComplete', handleRouteChange);
        };
    }, [router]);

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="description" content="Generated by create next app" />
            </Head>
            <NavBar />
            <Component {...pageProps} />
            <Footer />
        </>
    );
}

export default MyApp;
